### ISSUE TITLE
Deepworld IOS 2.11.0.1 Error 

### ISSUE THREAD

**Issue by Lanchochik228** [kuroppoi/brainwine#27] opened 2023-08-04 09:53 UTC
I edited the Api.json file Everything was fine I wrote the same port as in the instructions I started the server I went to Deepworld on my IPhone Xs I created a new character And I get an error " Error A networking error occurred ( #61 - Connection Refused ) " I tried pro edit api.json I entered the port "game_server_ip" and on the "game_server_port" port - 5002 And when I enter the game in the console, I write Something like My phone and if I exit the game, then the console writes Network reset by peer How to understand this?

**Comment by kuroppoi** [comment] 2023-12-29 15:59
Bit hard to pinpoint the issue -- could be the firewall blocking communication, an incorrectly patched client or an incorrectly configured server. Closing this since it's quite old at this point but feel free to open a new one if the issue is still relevant.

**Closed by kuroppoi** 2023-12-29 15:59 UTC
